/**
 * useOffers — single source of truth for all offers across the app.
 *
 * Offers are persisted to the DB via /api/v1/offers.php.
 * The module-level _offers ref is shared between the dashboard and the /deals
 * page so that a newly-created offer is visible on both instantly.
 */
import { ref, computed } from 'vue'

import { destinations as demoDestinations, packages as demoPackages, services as demoServices, offers as demoOffers } from '@/data/content.js'

const API = '/arrivo-website/backend/api/v1'

// ── Module-level state (singleton) ───────────────────────────────────────────
const _offers = ref([...demoOffers])
const _loading = ref(false)
const _loaded = ref(false)

// Auto-fetch all active public offers the moment the module is first imported.
async function _bootstrap() {
  if (_loaded.value || _loading.value) return
  _loading.value = true
  try {
    const res = await fetch(`${API}/offers.php`)
    const data = await res.json()
    if (data.offers) {
      // Merge: avoid duplicates if demo offers were somehow in the DB
      data.offers.forEach(dbOff => {
        if (!_offers.value.some(o => o.offerID === dbOff.offerID)) {
          _offers.value.push(dbOff)
        }
      })
    }
    _loaded.value = true
  } catch (e) {
    console.warn('[useOffers] Failed to load offers:', e)
  } finally {
    _loading.value = false
  }
}
_bootstrap()

// ── Composable ────────────────────────────────────────────────────────────────
export function useOffers() {
  // ── Reads ──────────────────────────────────────────────────────────────────
  const allOffers = computed(() => _offers.value)
  const activeOffers = computed(() => _offers.value.filter(o => o.active !== false))
  const collabOffers = computed(() => _offers.value.filter(o => o.source === 'collab'))
  const manualOffers = computed(() => _offers.value.filter(o => o.source !== 'collab'))

  // Returns only this user's non-collab offers (for the dashboard panel)
  function userOffers(userId) {
    return computed(() =>
      _offers.value.filter(o => o.source !== 'collab' && o.owner_id === Number(userId))
    )
  }
  // ── Writes — in-memory state mutations ────────────────────────────────────
  function addOffer(offer) {
    _offers.value.unshift({
      ...offer,
      offerID: offer.offerID ?? Date.now(),
      active:  offer.active  ?? true,
      source:  offer.source  ?? 'manual',
    })
  }

  function updateOffer(updated) {
    const idx = _offers.value.findIndex(o => o.offerID === updated.offerID)
    if (idx !== -1) _offers.value[idx] = { ..._offers.value[idx], ...updated }
  }

  function deleteOffer(offerID) {
    _offers.value = _offers.value.filter(o => o.offerID !== offerID)
  }

  // ── Writes — persisted to the DB ──────────────────────────────────────────
  async function saveOfferToDB(offer) {
    try {
      const isNew = !offer.offerID || typeof offer.offerID === 'number' && offer.offerID > 1e10
      // offerID > 1e10 means it was generated by Date.now() — not a real DB id

      if (isNew) {
        const res = await fetch(`${API}/offers.php`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(offer),
        })
        const data = await res.json()
        if (!res.ok) throw new Error(data.error || 'Failed to create offer')
        // Add to local store with the real DB id
        addOffer({ ...offer, offerID: data.offer_id })
      } else {
        const res = await fetch(`${API}/offers.php`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...offer, id: offer.offerID }),
        })
        const data = await res.json()
        if (!res.ok) throw new Error(data.error || 'Failed to update offer')
        updateOffer(offer)
      }
    } catch (e) {
      console.error('[useOffers] saveOfferToDB error:', e)
    }
  }

  async function deleteOfferFromDB(offerID) {
    try {
      const res = await fetch(`${API}/offers.php`, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: offerID }),
      })
      if (!res.ok) {
        const data = await res.json()
        throw new Error(data.error || 'Failed to delete offer')
      }
      deleteOffer(offerID)
    } catch (e) {
      console.error('[useOffers] deleteOfferFromDB error:', e)
    }
  }

  // Legacy alias kept for collab flows that call saveOffer directly
  function saveOffer(offer) {
    const exists = _offers.value.some(o => o.offerID === offer.offerID)
    exists ? updateOffer(offer) : addOffer(offer)
  }

  return {
    allOffers,
    activeOffers,
    collabOffers,
    manualOffers,
    userOffers,
    loading: _loading,
    addOffer,
    updateOffer,
    deleteOffer,
    deleteOfferFromDB,
    saveOffer,
    saveOfferToDB,
  }
}